[theme]
base = "dark"
primaryColor = "#14B8A6"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#1E293B"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500
